;METADATA=(Diff=true, UseCommands=true)
[/Script/ShooterGame.ShooterGameMode]
BabyImprintingStatScaleMultiplier=0.999989986
BabyCuddleIntervalMultiplier=0.0299999993
BabyCuddleGracePeriodMultiplier=0.999989986
BabyCuddleLoseImprintQualitySpeedMultiplier=0.999989986
PerLevelStatsMultiplier_DinoTamed[0]=0.0900000036
PerLevelStatsMultiplier_DinoTamed[1]=0.999989986
PerLevelStatsMultiplier_DinoTamed[2]=0.999989986
PerLevelStatsMultiplier_DinoTamed[3]=0.999989986
PerLevelStatsMultiplier_DinoTamed[4]=0.999989986
PerLevelStatsMultiplier_DinoTamed[5]=0.999989986
PerLevelStatsMultiplier_DinoTamed[6]=0.999989986
PerLevelStatsMultiplier_DinoTamed[7]=0.999989986
PerLevelStatsMultiplier_DinoTamed[8]=0.0700000003
PerLevelStatsMultiplier_DinoTamed[9]=0.999989986
PerLevelStatsMultiplier_DinoTamed[10]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[0]=0.0399900004
PerLevelStatsMultiplier_DinoTamed_Add[1]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[2]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[3]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[4]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[5]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[6]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[7]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[8]=0.0399900004
PerLevelStatsMultiplier_DinoTamed_Add[9]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Add[10]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=0.189999998
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[2]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[3]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[4]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[5]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[6]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[7]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.189999998
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=0.999989986
PerLevelStatsMultiplier_DinoTamed_Affinity[10]=0.999989986
PerLevelStatsMultiplier_DinoWild[0]=0.999989986
PerLevelStatsMultiplier_DinoWild[1]=0.999989986
PerLevelStatsMultiplier_DinoWild[2]=0.999989986
PerLevelStatsMultiplier_DinoWild[3]=0.999989986
PerLevelStatsMultiplier_DinoWild[4]=0.999989986
PerLevelStatsMultiplier_DinoWild[5]=0.999989986
PerLevelStatsMultiplier_DinoWild[6]=0.999989986
PerLevelStatsMultiplier_DinoWild[7]=0.999989986
PerLevelStatsMultiplier_DinoWild[8]=0.999989986
PerLevelStatsMultiplier_DinoWild[9]=0.999989986
PerLevelStatsMultiplier_DinoWild[10]=0.999989986
PerLevelStatsMultiplier_Player[0]=0.999989986
PerLevelStatsMultiplier_Player[1]=0.999989986
PerLevelStatsMultiplier_Player[2]=0.999989986
PerLevelStatsMultiplier_Player[3]=0.999989986
PerLevelStatsMultiplier_Player[4]=0.999989986
PerLevelStatsMultiplier_Player[5]=0.999989986
PerLevelStatsMultiplier_Player[6]=0.999989986
PerLevelStatsMultiplier_Player[7]=0.999989986
PerLevelStatsMultiplier_Player[8]=0.999989986
PerLevelStatsMultiplier_Player[9]=0.999989986
PerLevelStatsMultiplier_Player[10]=0.999989986
ItemStatClamps[1]=19800
ItemStatClamps[3]=19800
GlobalSpoilingTimeMultiplier=0
GlobalItemDecompositionTimeMultiplier=0
GlobalCorpseDecompositionTimeMultiplier=1
PvPZoneStructureDamageMultiplier=6
StructureDamageRepairCooldown=179.999893
IncreasePvPRespawnIntervalCheckPeriod=300.000031
IncreasePvPRespawnIntervalMultiplier=1.99998999
IncreasePvPRespawnIntervalBaseAmount=59.9999809
ResourceNoReplenishRadiusPlayers=0.200000003
ResourceNoReplenishRadiusStructures=0.500150025
CropGrowthSpeedMultiplier=0.999989986
LayEggIntervalMultiplier=0.999989986
PoopIntervalMultiplier=0.999989986
CropDecaySpeedMultiplier=0.999989986
MatingIntervalMultiplier=0.00100000005
EggHatchSpeedMultiplier=30
BabyMatureSpeedMultiplier=100
BabyFoodConsumptionSpeedMultiplier=0.999989986
DinoTurretDamageMultiplier=0.999989986
DinoHarvestingDamageMultiplier=3.19999003
PlayerHarvestingDamageMultiplier=0.999989986
CustomRecipeEffectivenessMultiplier=0.999989986
CustomRecipeSkillMultiplier=0.999989986
AutoPvEStartTimeSeconds=0
AutoPvEStopTimeSeconds=0
KillXPMultiplier=0.999989986
HarvestXPMultiplier=0.999989986
CraftXPMultiplier=0.999989986
GenericXPMultiplier=0.999989986
SpecialXPMultiplier=0.999989986
FuelConsumptionIntervalMultiplier=1
PhotoModeRangeLimit=9000
bDisablePhotoMode=False
bIncreasePvPRespawnInterval=True
bAutoPvETimer=False
bAutoPvEUseSystemTime=False
bDisableFriendlyFire=False
bFlyerPlatformAllowUnalignedDinoBasing=True
bDisableLootCrates=False
bAllowCustomRecipes=True
bPassiveDefensesDamageRiderlessDinos=True
bPvEAllowTribeWar=True
bPvEAllowTribeWarCancel=True
MaxDifficulty=True
bUseSingleplayerSettings=False
bUseCorpseLocator=True
bShowCreativeMode=False
bHardLimitTurretsInRange=True
bDisableStructurePlacementCollision=False
bAllowPlatformSaddleMultiFloors=False
bAllowUnlimitedRespecs=True
bDisableDinoRiding=False
bDisableDinoTaming=False
OverrideMaxExperiencePointsPlayer=0
OverrideMaxExperiencePointsDino=0
MaxNumberOfPlayersInTribe=0
ExplorerNoteXPMultiplier=0.999989986
BossKillXPMultiplier=0.999989986
AlphaKillXPMultiplier=0.999989986
WildKillXPMultiplier=0.999989986
CaveKillXPMultiplier=0.999989986
TamedKillXPMultiplier=0.999989986
UnclaimedKillXPMultiplier=0.999989986
SupplyCrateLootQualityMultiplier=1
FishingLootQualityMultiplier=1
CraftingSkillBonusMultiplier=1
bAllowSpeedLeveling=False
bAllowFlyerSpeedLeveling=False
bDisableDefaultDinoTaming=False
NPCReplacements=(FromClassName="AcrocanthosaurusAA_Character_BP_C",ToClassName="Acrocanthosaurus_Character_BP_C")
NPCReplacements=(FromClassName="Asc_AcrocanthosaurusAA_Character_BP_C",ToClassName="Acrocanthosaurus_Character_BP_C")
NPCReplacements=(FromClassName="XiphactinusAA_Character_BP_C",ToClassName="Xiphactinus_Character_BP_ASA_C")
NPCReplacements=(FromClassName="HelicoprionAA_Character_BP_C",ToClassName="Helicoprion_Character_BP_C")
NPCReplacements=(FromClassName="PaleoDodoRexy_Character_BP_C",ToClassName="")
NPCReplacements=(FromClassName="DodoRexy_Character_BP_C",ToClassName="")
NPCReplacements=(FromClassName="DodorexyLanternPet_Character_BP_C",ToClassName="")
NPCReplacements=(FromClassName="EletricDodoRexy_Character_BP_C",ToClassName="")
NPCReplacements=(FromClassName="LanternDodoRexy_Character_BP_C",ToClassName="")
NPCReplacements=(FromClassName="ABDodoRexy_Character_BP_C",ToClassName="")
NPCReplacements=(FromClassName="S-Fenrir_Character_BP_C",ToClassName="")
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_RatfishTreats_C",EngramHidden=true,EngramPointsCost=0,EngramLevelRequirement=1,RemoveEngramPreReq=true)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Saddle_GHelicoprion_C",EngramHidden=true,EngramPointsCost=0,EngramLevelRequirement=1,RemoveEngramPreReq=true)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Saddle_Xiphactinus_C",EngramHidden=true,EngramPointsCost=0,EngramLevelRequirement=1,RemoveEngramPreReq=true)
OverrideNamedEngramEntries=(EngramClassName="AAAcro/Dinos/Saddle/EngramEntry_SaddleAcro.EngramEntry_SaddleAcro_C",EngramHidden=true,EngramPointsCost=0,EngramLevelRequirement=1,RemoveEngramPreReq=true)
OverrideNamedEngramEntries=(EngramClassName="EngramDigitizerRailGun_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=86,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramDigitizerRifle_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=86,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramDinoballStorageBox_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=50,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramDepotTerminal_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=50,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramDinoball_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=50,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramDinoballStack_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=50,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramDepotPad_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=86,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramDepotGeneStorage_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=86,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramEntryDinoballDisplayCase_C",EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=35,RemoveEngramPreReq=True)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Dodorex_BossEasy_C",EngramHidden=true,EngramPointsCost=0,EngramLevelRequirement=1,RemoveEngramPreReq=true)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Dodorex_BossMed_C",EngramHidden=true,EngramPointsCost=0,EngramLevelRequirement=1,RemoveEngramPreReq=true)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Dodorex_BossHard_C",EngramHidden=true,EngramPointsCost=0,EngramLevelRequirement=1,RemoveEngramPreReq=true)
ConfigOverrideItemCraftingCosts=(ItemClassString="ItemWeaponDigitizerRailGun_C", BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_ChitinPaste_C", BaseResourceRequirement=25.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_MetalIngot_C", BaseResourceRequirement=15.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Polymer_C", BaseResourceRequirement=30.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Electronics_C", BaseResourceRequirement=10.0, bCraftingRequireExactResourceType=False)))
ConfigOverrideItemCraftingCosts=(ItemClassString="ItemWeaponDigitizerRifle_C", BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_ChitinPaste_C", BaseResourceRequirement=25.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_MetalIngot_C", BaseResourceRequirement=15.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Polymer_C", BaseResourceRequirement=30.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Electronics_C", BaseResourceRequirement=10.0, bCraftingRequireExactResourceType=False)))
ConfigOverrideItemCraftingCosts=(ItemClassString="ItemStructureDepotTerminal_C", BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_Crystal_C", BaseResourceRequirement=12.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Electronics_C", BaseResourceRequirement=7.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_MetalIngot_C", BaseResourceRequirement=115.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Polymer_C", BaseResourceRequirement=30.0, bCraftingRequireExactResourceType=False)))
ConfigOverrideItemCraftingCosts=(ItemClassString="ItemDinoballStorageBox_C", BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_Crystal_C", BaseResourceRequirement=5.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Electronics_C", BaseResourceRequirement=5.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_MetalIngot_C", BaseResourceRequirement=60.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Polymer_C", BaseResourceRequirement=15.0, bCraftingRequireExactResourceType=False)))
ConfigOverrideItemCraftingCosts=(ItemClassString="ItemDepotPad_C", BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_BlackPearl_C", BaseResourceRequirement=10.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Electronics_C", BaseResourceRequirement=10.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_MetalIngot_C", BaseResourceRequirement=40.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_SilicaPearls_C", BaseResourceRequirement=30.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Polymer_C", BaseResourceRequirement=60.0, bCraftingRequireExactResourceType=False)))
ConfigOverrideItemCraftingCosts=(ItemClassString="ItemStructureDepotGeneStorage_C", BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_Crystal_C", BaseResourceRequirement=500.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_MetalIngot_C", BaseResourceRequirement=700.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_Polymer_C", BaseResourceRequirement=220.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_ChitinPaste_C", BaseResourceRequirement=440.0, bCraftingRequireExactResourceType=False),(ResourceItemTypeString="PrimalItemResource_SilicaPearls_C", BaseResourceRequirement=360.0, bCraftingRequireExactResourceType=False)))
ConfigOverrideItemCraftingCosts=(ItemClassString="ItemStructureDinoballDisplayCase_C",BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_MetalIngot_C",BaseResourceRequirement=4.0,bCostIncreasePerLevel=false),(ResourceItemTypeString="PrimalItemResource_ChitinPaste_C",BaseResourceRequirement=10.0,bCostIncreasePerLevel=false),(ResourceItemTypeString="PrimalItemResource_Electronics_C",BaseResourceRequirement=5.0,bCostIncreasePerLevel=false)))

[ShooterGameMode_TEMPOverrides]
bUseCorpseLocator=True
